version: "3.9"
services:
  postgres :
    build:
      context: deploy/postgres
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: on-failure
    environment:
      - POSTGRES_PORT=5333
      - POSTGRES_HOST=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - POSTGRES_USER=${POSTGRES_SUPERUSER}
      - POSTGRES_PASSWORD=${POSTGRES_SUPERUSER_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_SUPERUSER} -p 5333" ]
      interval: 3s
      timeout: 5s
      retries: 10
    ports:
      - "5333:5333"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/manufacturing
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: