version: "3.3"
services:
  db :
    image: postgres
    volumes:
      - data:/varlib/postgresql/data
    env_file:
      - ./.env

    networks:
      - engineer-network
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
#    command: gunicorn manufacturing.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/manufacturing
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - engineer-network
#  nginx:
#    build: ./nginx
#    ports:
#      - "80:80"
#    depends_on:
#      - web
#      - db
#    networks:
#      - engineer-network

networks:
  engineer-network:
    driver: bridge
volumes:
  data: