# Generated by Django 4.0.3 on 2023-05-19 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Наименование')),
                ('slug', models.CharField(max_length=60, unique=True, verbose_name='Поле slug')),
            ],
            options={
                'verbose_name': 'Сборочная единица',
                'verbose_name_plural': 'Сборочные единицы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Наименование')),
                ('slug', models.CharField(max_length=60, unique=True, verbose_name='Поле slug')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Наименование')),
                ('slug', models.CharField(max_length=60, unique=True, verbose_name='Поле slug')),
                ('machine', models.CharField(max_length=60, unique=True, verbose_name='Наименование оборудования')),
            ],
            options={
                'verbose_name': 'Трудоемкость',
                'verbose_name_plural': 'Трудоемкость',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ManufacturingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Поле slug')),
            ],
            options={
                'verbose_name': 'План производства',
                'verbose_name_plural': 'Планы производства',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Наименование')),
                ('slug', models.CharField(max_length=60, unique=True, verbose_name='Поле slug')),
                ('unit', models.CharField(default='кг', max_length=20, verbose_name='Единица измерения')),
                ('price_per_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость за метр')),
                ('price_per_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость за тонну')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MPResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Поле slug')),
            ],
            options={
                'verbose_name': 'Ресурсы плана производства',
                'verbose_name_plural': 'Ресурсы планов производства',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Поле slug')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StandardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Поле slug')),
                ('unit', models.CharField(blank=True, default='шт.', max_length=20, null=True, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Стандартное изделие',
                'verbose_name_plural': 'Стандартные изделия',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductStandardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Количество')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.product')),
                ('standard_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.standarddetail')),
            ],
            options={
                'ordering': ('standard_detail',),
            },
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Количество')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.material')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.product')),
            ],
            options={
                'ordering': ('material',),
            },
        ),
        migrations.CreateModel(
            name='ProductLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Количество')),
                ('labor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.labor')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.product')),
            ],
            options={
                'ordering': ('labor',),
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.detail')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.product')),
            ],
            options={
                'ordering': ('detail',),
            },
        ),
        migrations.CreateModel(
            name='ProductAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('assembly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.assembly')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.product')),
            ],
            options={
                'ordering': ('assembly',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='assemblies',
            field=models.ManyToManyField(through='cost.ProductAssembly', to='cost.assembly'),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.ManyToManyField(through='cost.ProductDetail', to='cost.detail'),
        ),
        migrations.AddField(
            model_name='product',
            name='labors',
            field=models.ManyToManyField(through='cost.ProductLabor', to='cost.labor'),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(through='cost.ProductMaterial', to='cost.material'),
        ),
        migrations.AddField(
            model_name='product',
            name='standard_details',
            field=models.ManyToManyField(through='cost.ProductStandardDetail', to='cost.standarddetail'),
        ),
        migrations.CreateModel(
            name='MPResourcesStandardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Количество')),
                ('mp_resources', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.mpresources')),
                ('standard_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.standarddetail')),
            ],
            options={
                'ordering': ('standard_detail',),
            },
        ),
        migrations.CreateModel(
            name='MPResourcesMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Количество')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.material')),
                ('mp_resources', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.mpresources')),
            ],
            options={
                'ordering': ('material',),
            },
        ),
        migrations.CreateModel(
            name='MPResourcesLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Количество')),
                ('labor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.labor')),
                ('mp_resources', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.mpresources')),
            ],
            options={
                'ordering': ('labor',),
            },
        ),
        migrations.AddField(
            model_name='mpresources',
            name='labors',
            field=models.ManyToManyField(through='cost.MPResourcesLabor', to='cost.labor'),
        ),
        migrations.AddField(
            model_name='mpresources',
            name='materials',
            field=models.ManyToManyField(through='cost.MPResourcesMaterial', to='cost.material'),
        ),
        migrations.AddField(
            model_name='mpresources',
            name='standard_details',
            field=models.ManyToManyField(through='cost.MPResourcesStandardDetail', to='cost.standarddetail'),
        ),
        migrations.CreateModel(
            name='MPProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('mp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.manufacturingplan')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.product')),
            ],
        ),
        migrations.CreateModel(
            name='MPLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Количество')),
                ('labor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.labor')),
                ('mp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.manufacturingplan')),
            ],
            options={
                'ordering': ('mp',),
            },
        ),
        migrations.CreateModel(
            name='MPDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.detail')),
                ('mp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.manufacturingplan')),
            ],
        ),
        migrations.CreateModel(
            name='MPAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('assembly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.assembly')),
                ('mp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.manufacturingplan')),
            ],
        ),
        migrations.AddField(
            model_name='manufacturingplan',
            name='assemblies',
            field=models.ManyToManyField(through='cost.MPAssembly', to='cost.assembly'),
        ),
        migrations.AddField(
            model_name='manufacturingplan',
            name='details',
            field=models.ManyToManyField(through='cost.MPDetail', to='cost.detail'),
        ),
        migrations.AddField(
            model_name='manufacturingplan',
            name='labors',
            field=models.ManyToManyField(through='cost.MPLabor', to='cost.labor'),
        ),
        migrations.AddField(
            model_name='manufacturingplan',
            name='products',
            field=models.ManyToManyField(through='cost.MPProduct', to='cost.product'),
        ),
        migrations.CreateModel(
            name='DetailMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Количество')),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.detail')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.material')),
            ],
            options={
                'ordering': ('material',),
            },
        ),
        migrations.CreateModel(
            name='DetailLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Количество')),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.detail')),
                ('labor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.labor')),
            ],
            options={
                'ordering': ('labor',),
            },
        ),
        migrations.AddField(
            model_name='detail',
            name='labors',
            field=models.ManyToManyField(through='cost.DetailLabor', to='cost.labor'),
        ),
        migrations.AddField(
            model_name='detail',
            name='materials',
            field=models.ManyToManyField(through='cost.DetailMaterial', to='cost.material'),
        ),
        migrations.CreateModel(
            name='AssemblyStandardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Количество')),
                ('assembly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.assembly')),
                ('standard_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.standarddetail')),
            ],
            options={
                'ordering': ('standard_detail',),
            },
        ),
        migrations.CreateModel(
            name='AssemblyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Количество')),
                ('assembly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.assembly')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.material')),
            ],
            options={
                'ordering': ('material',),
            },
        ),
        migrations.CreateModel(
            name='AssemblyLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Количество')),
                ('assembly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.assembly')),
                ('labor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.labor')),
            ],
            options={
                'ordering': ('labor',),
            },
        ),
        migrations.CreateModel(
            name='AssemblyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('assembly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.assembly')),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost.detail')),
            ],
            options={
                'ordering': ('detail',),
            },
        ),
        migrations.AddField(
            model_name='assembly',
            name='details',
            field=models.ManyToManyField(through='cost.AssemblyDetail', to='cost.detail'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='labors',
            field=models.ManyToManyField(through='cost.AssemblyLabor', to='cost.labor'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='materials',
            field=models.ManyToManyField(through='cost.AssemblyMaterial', to='cost.material'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='standard_details',
            field=models.ManyToManyField(through='cost.AssemblyStandardDetail', to='cost.standarddetail'),
        ),
    ]
