# Generated by Django 4.0.3 on 2023-05-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cost", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="price_per_meter",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Стоимость за метр",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="price_per_ton",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Стоимость за тонну",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(
                max_length=60, unique=True, verbose_name="Наименование"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="unit",
            field=models.CharField(
                default="кг", max_length=20, verbose_name="Единица измерения"
            ),
        ),
    ]
